version: 2.1
orbs:
    python: circleci/python@0.3.2
    codecov: codecov/codecov@1.0.2

jobs:
    build:
        executor: python/default
        steps:
            - checkout
            - python/load-cache
            - python/install-deps
            - python/save-cache
            - run:
                command: |
                    pip install .
                name: Install ECHO
            - run:
                command: |
                    flake8 .
                    flake8 . --exit-zero --select=E,F,W,C90 --max-complexity=10 --max-line-length=127
                name: run flake8
            - run:
                command: |
                    pre-commit run --all-files
                name: run pre-commit
            - run:
                command: |
                    pytest --cov=./ --cov-report xml --cov-config=setup.cfg
            - codecov/upload:
                file: coverage.xml
                token: d4e7e70e-d786-412a-8299-ec9cf91eba01

#Build our module, flake8, run tests
workflows:
  build_and_test:
    jobs:
      - build
